const fs = require('fs');
let content = fs.readFileSync('c:/Users/cii/Desktop/Haşere İlaçlama/frontend/src/App.jsx', 'utf8');

const r = '\ufffd';

const replacements = {
  [`Y${r}NETİCİ`]: "YÖNETİCİ",
  [`Y${r}NET${r}C${r}`]: "YÖNETİCİ",
  [`${r}zet Rapor`]: "Özet Rapor",
  [`${r}S${r} Görev`]: "✓ Görev",
  [`MOD${r}SL${r}S`]: "MODÜLÜ",
  [`istedi${r}inize`]: "istediğinize",
  [`istedi${r}iniz`]: "istediğiniz",
  [`istedi${r}i`]: "istediği",
  [`ba${r}arıyla`]: "başarıyla",
  [`yerle${r}im`]: "yerleşim",
  [`yerle${r}ti`]: "yerleşti",
  [`Yerle${r}im`]: "Yerleşim",
  [`klenmi${r}`]: "klenmiş",
  [`${r}Szerine`]: "Üzerine",
  [`${r}SNC${r}S`]: "ÜNCÜ",
  [`venli${r}i`]: "venliği",
  [`istatisti${r}i`]: "istatistiği",
  [`girilmedi${r}i`]: "girilmediği",
  [`olu${r}tur`]: "oluştur",
  [`Olu${r}tur`]: "Oluştur",
  [`olu${r}tu`]: "oluştu",
  [`klendi${r}i`]: "klendiği",
  [`gelindi${r}i`]: "gelindiği",
  [`edilmi${r}`]: "edilmiş",
  [`geni${r}let`]: "genişlet",
  [`LA${r}LAMA`]: "LAÇLAMA",
  [`ha${r}ere`]: "haşere",
  [`Ha${r}ere`]: "Haşere",
  [`kar${r}ı`]: "karşı",
  [`ekle${r}en`]: "ekleşen",
  [`tirilmi${r}`]: "tirilmiş",
  [`${r}Sretici`]: "Üretici",
  [`giri${r}i`]: "girişi",
  [`G${r}R${r}SN${r}SM${r}S`]: "GÖRÜNÜMÜ",
  [`G${r}R${r}SN${r}SM`]: "GÖRÜNÜM",
  [`R${r}SN${r}SM${r}S`]: "RÜNÜMÜ",
  [`R${r}SN${r}SM`]: "RÜNÜM",
  [`kaydedilmemi${r}`]: "kaydedilmemiş",
  [`G${r}SNL${r}SK`]: "GÜNLÜK",
  [`G${r}SNCELLEME`]: "GÜNCELLEME",
  [`D${r}SZENLEME`]: "DÜZENLEME",
  [`Yetersizli${r}i`]: "Yetersizliği",
  [`birle${r}tir`]: "birleştir",
  [`Biti${r}`]: "Bitiş",
  [`G${r}SVENL`]: "GÜVENLİ",
  [`kaydetti${r}iniz`]: "kaydettiğiniz",
  [`R${r}SNT${r}SLEME`]: "RÜNTÜLEME",
  [`nderilmi${r}`]: "nderilmiş",
  [`${r}SR${r}SNE`]: "ÜRÜNE",
  [`${r}SR${r}SN`]: "ÜRÜN",
  [`M${r}SŞTERİ`]: "MÜŞTERİ",
  [`L${r}SM`]: "LÜM",
  [`ya${r}a`]: "yaşa",
  [`ba${r}la`]: "başla",
  [`Ba${r}la`]: "Başla",
  [`grafi${r}i`]: "grafiği",
  [`i${r}in`]: "için",
  [`ce${r}i`]: "ceği",
  [`Yo${r}unlu`]: "Yoğunlu",
  [`unlu${r}u`]: "unluğu",
  [`Di${r}er`]: "Diğer",
  [`B${r}l`]: "Böl",
  [`yo${r}un`]: "yoğun",
  [`De${r}er`]: "Değer",
  [`R${r}zgar`]: "Rüzgar",
  [`Ya${r}mur`]: "Yağmur",
  [`ne${r}i`]: "neği",
  [`de${r}il`]: "değil",
  [`ti${r}i`]: "tiği",
  [`ar${r}ı`]: "araç",
  [`K${r}rfez`]: "Körfez",
  [`Bo${r}luk`]: "Boşluk",
  [`Do${r}ru`]: "Doğru",
  [`So${r}uk`]: "Soğuk",
  [`E${r}itim`]: "Eğitim",
  [`ene${r}i`]: "eneği",
  [`ki${r}i`]: "kişi",
  [`Ar${r}a`]: "Araça",
  [`Sa${r}la`]: "Sağla",
  [`Ho${r}geldin`]: "Hoşgeldin",
  [`da${r}ı`]: "dağı",
  [`di${r}er`]: "diğer",
  [`oldu${r}u`]: "olduğu",
  [`Da${r}ıtım`]: "Dağıtım",
  [`e${r}le`]: "eşle",
  [`sa${r}la`]: "sağla",
  [`Ka${r}ak`]: "Kaçak",
  [`${r}a${r}`]: "çağ",
  [`${r}S`]: "Ü",
  [`${r}R`]: "ÜR",
};

for (const [bad, good] of Object.entries(replacements)) {
  content = content.replace(new RegExp(bad.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'), good);
}

fs.writeFileSync('c:/Users/cii/Desktop/Haşere İlaçlama/frontend/src/App.jsx', content, 'utf8');
console.log('Fixed massive list of UI strings');
